version: '3'
services:
  postgres:
    image: daafonsecato/kataterm-postgres:v2
    build:
      context: ./database
      dockerfile: Dockerfile
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: your_username
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: your_database_name
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - quizard_network

  frontend:
    image: daafonsecato/kataterm-frontend:v2
    build:
      context: ./frontend
      dockerfile: Dockerfile.develop
    ports:
      - 80:3000
    volumes:
      - ./frontend:/app
    environment:
      - NODE_ENV=development
    env_file:
      - ./frontend/.env
    networks:
      - quizard_network

  backend:
    image: daafonsecato/kataterm-backend:v2
    build:
      context: ./backend
      dockerfile: Dockerfile.develop
    ports:
      - 8000:8000
    env_file:
      - ./backend/.env
    depends_on:
      - postgres
    volumes:
      - ./backend:/app
    environment:
      - NODE_ENV=development
    networks:
      - quizard_network

  reverseproxy:
    image: daafonsecato/kataterm-reverseproxy:v2
    build:
      context: ./reverseproxy
      dockerfile: Dockerfile
    ports:
      - 7070:7070
      - 9090:9090
    env_file:
      - ./reverseproxy/.env
    depends_on:
      - postgres
    volumes:
      - ./reverseproxy:/app
      - /home/ubuntu/.aws/credentials:/root/.aws/credentials
    networks:
      - quizard_network

  gitkatas:
    image: daafonsecato/kataterm-gitkatas:v2
    build:
      context: ./gitkatas
      dockerfile: Dockerfile.gitkatas
    env_file:
      - ./gitkatas/.env
    ports:
      - 7681:7681
      - 8080:8080
      - 8095:8095
    volumes:
      - ./gitkatas:/app
      - ./ch1-git-katas/exercise:/home/git-katas-user/exercise
    networks:
      - quizard_network

  validator:
    image: daafonsecato/kataterm-validator:v2
    build:
      context: ./validator
      dockerfile: Dockerfile.validator
    env_file:
      - ./validator/.env
    ports:
      - 8096:8096
    volumes:
      - ./validator:/app
      - ./ch1-git-katas/validation:/validation
      - ./ch1-git-katas/exercise:/exercise
    networks:
      - quizard_network

networks:
  quizard_network:
    driver: bridge

volumes:
  postgres_data:

